//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SACCOPortal.NAVWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Portals_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Portals")]
    public partial class Portals : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FnUpdatePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback MiniStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnMemberStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnFosaStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback FndividentstatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnLoanGuranteedOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnLoanRepaymentSheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnLoanGurantorsReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnAtmApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnAtmBlockingOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnChangePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Portals() {
            this.Url = global::SACCOPortal.Properties.Settings.Default.SACCOPortal_NAVWS_Portals;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FnUpdatePasswordCompletedEventHandler FnUpdatePasswordCompleted;
        
        /// <remarks/>
        public event MiniStatementCompletedEventHandler MiniStatementCompleted;
        
        /// <remarks/>
        public event FnMemberStatementCompletedEventHandler FnMemberStatementCompleted;
        
        /// <remarks/>
        public event FnFosaStatementCompletedEventHandler FnFosaStatementCompleted;
        
        /// <remarks/>
        public event FndividentstatementCompletedEventHandler FndividentstatementCompleted;
        
        /// <remarks/>
        public event FnLoanGuranteedCompletedEventHandler FnLoanGuranteedCompleted;
        
        /// <remarks/>
        public event FnLoanRepaymentSheduleCompletedEventHandler FnLoanRepaymentSheduleCompleted;
        
        /// <remarks/>
        public event FnLoanGurantorsReportCompletedEventHandler FnLoanGurantorsReportCompleted;
        
        /// <remarks/>
        public event FnAtmApplicationsCompletedEventHandler FnAtmApplicationsCompleted;
        
        /// <remarks/>
        public event FnAtmBlockingCompletedEventHandler FnAtmBlockingCompleted;
        
        /// <remarks/>
        public event FnChangePasswordCompletedEventHandler FnChangePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnUpdatePassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnUpdatePassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnUpdatePassword(string memberNo, string idNo, string newPassword) {
            object[] results = this.Invoke("FnUpdatePassword", new object[] {
                        memberNo,
                        idNo,
                        newPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnUpdatePasswordAsync(string memberNo, string idNo, string newPassword) {
            this.FnUpdatePasswordAsync(memberNo, idNo, newPassword, null);
        }
        
        /// <remarks/>
        public void FnUpdatePasswordAsync(string memberNo, string idNo, string newPassword, object userState) {
            if ((this.FnUpdatePasswordOperationCompleted == null)) {
                this.FnUpdatePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnUpdatePasswordOperationCompleted);
            }
            this.InvokeAsync("FnUpdatePassword", new object[] {
                        memberNo,
                        idNo,
                        newPassword}, this.FnUpdatePasswordOperationCompleted, userState);
        }
        
        private void OnFnUpdatePasswordOperationCompleted(object arg) {
            if ((this.FnUpdatePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnUpdatePasswordCompleted(this, new FnUpdatePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:MiniStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="MiniStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string MiniStatement(string memberNo) {
            object[] results = this.Invoke("MiniStatement", new object[] {
                        memberNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MiniStatementAsync(string memberNo) {
            this.MiniStatementAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void MiniStatementAsync(string memberNo, object userState) {
            if ((this.MiniStatementOperationCompleted == null)) {
                this.MiniStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMiniStatementOperationCompleted);
            }
            this.InvokeAsync("MiniStatement", new object[] {
                        memberNo}, this.MiniStatementOperationCompleted, userState);
        }
        
        private void OnMiniStatementOperationCompleted(object arg) {
            if ((this.MiniStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MiniStatementCompleted(this, new MiniStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnMemberStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnMemberStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnMemberStatement(string memberNo, string path) {
            this.Invoke("FnMemberStatement", new object[] {
                        memberNo,
                        path});
        }
        
        /// <remarks/>
        public void FnMemberStatementAsync(string memberNo, string path) {
            this.FnMemberStatementAsync(memberNo, path, null);
        }
        
        /// <remarks/>
        public void FnMemberStatementAsync(string memberNo, string path, object userState) {
            if ((this.FnMemberStatementOperationCompleted == null)) {
                this.FnMemberStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnMemberStatementOperationCompleted);
            }
            this.InvokeAsync("FnMemberStatement", new object[] {
                        memberNo,
                        path}, this.FnMemberStatementOperationCompleted, userState);
        }
        
        private void OnFnMemberStatementOperationCompleted(object arg) {
            if ((this.FnMemberStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnMemberStatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnFosaStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnFosaStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnFosaStatement(string account_No, string path) {
            this.Invoke("FnFosaStatement", new object[] {
                        account_No,
                        path});
        }
        
        /// <remarks/>
        public void FnFosaStatementAsync(string account_No, string path) {
            this.FnFosaStatementAsync(account_No, path, null);
        }
        
        /// <remarks/>
        public void FnFosaStatementAsync(string account_No, string path, object userState) {
            if ((this.FnFosaStatementOperationCompleted == null)) {
                this.FnFosaStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnFosaStatementOperationCompleted);
            }
            this.InvokeAsync("FnFosaStatement", new object[] {
                        account_No,
                        path}, this.FnFosaStatementOperationCompleted, userState);
        }
        
        private void OnFnFosaStatementOperationCompleted(object arg) {
            if ((this.FnFosaStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnFosaStatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:Fndividentstatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="Fndividentstatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Fndividentstatement(string no, string path) {
            this.Invoke("Fndividentstatement", new object[] {
                        no,
                        path});
        }
        
        /// <remarks/>
        public void FndividentstatementAsync(string no, string path) {
            this.FndividentstatementAsync(no, path, null);
        }
        
        /// <remarks/>
        public void FndividentstatementAsync(string no, string path, object userState) {
            if ((this.FndividentstatementOperationCompleted == null)) {
                this.FndividentstatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFndividentstatementOperationCompleted);
            }
            this.InvokeAsync("Fndividentstatement", new object[] {
                        no,
                        path}, this.FndividentstatementOperationCompleted, userState);
        }
        
        private void OnFndividentstatementOperationCompleted(object arg) {
            if ((this.FndividentstatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FndividentstatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnLoanGuranteed", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnLoanGuranteed_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnLoanGuranteed(string member_No, string path) {
            this.Invoke("FnLoanGuranteed", new object[] {
                        member_No,
                        path});
        }
        
        /// <remarks/>
        public void FnLoanGuranteedAsync(string member_No, string path) {
            this.FnLoanGuranteedAsync(member_No, path, null);
        }
        
        /// <remarks/>
        public void FnLoanGuranteedAsync(string member_No, string path, object userState) {
            if ((this.FnLoanGuranteedOperationCompleted == null)) {
                this.FnLoanGuranteedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnLoanGuranteedOperationCompleted);
            }
            this.InvokeAsync("FnLoanGuranteed", new object[] {
                        member_No,
                        path}, this.FnLoanGuranteedOperationCompleted, userState);
        }
        
        private void OnFnLoanGuranteedOperationCompleted(object arg) {
            if ((this.FnLoanGuranteedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnLoanGuranteedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnLoanRepaymentShedule", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnLoanRepaymentShedule_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnLoanRepaymentShedule(string loan_No, string path) {
            this.Invoke("FnLoanRepaymentShedule", new object[] {
                        loan_No,
                        path});
        }
        
        /// <remarks/>
        public void FnLoanRepaymentSheduleAsync(string loan_No, string path) {
            this.FnLoanRepaymentSheduleAsync(loan_No, path, null);
        }
        
        /// <remarks/>
        public void FnLoanRepaymentSheduleAsync(string loan_No, string path, object userState) {
            if ((this.FnLoanRepaymentSheduleOperationCompleted == null)) {
                this.FnLoanRepaymentSheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnLoanRepaymentSheduleOperationCompleted);
            }
            this.InvokeAsync("FnLoanRepaymentShedule", new object[] {
                        loan_No,
                        path}, this.FnLoanRepaymentSheduleOperationCompleted, userState);
        }
        
        private void OnFnLoanRepaymentSheduleOperationCompleted(object arg) {
            if ((this.FnLoanRepaymentSheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnLoanRepaymentSheduleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnLoanGurantorsReport", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnLoanGurantorsReport_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnLoanGurantorsReport(string member_No, string path) {
            this.Invoke("FnLoanGurantorsReport", new object[] {
                        member_No,
                        path});
        }
        
        /// <remarks/>
        public void FnLoanGurantorsReportAsync(string member_No, string path) {
            this.FnLoanGurantorsReportAsync(member_No, path, null);
        }
        
        /// <remarks/>
        public void FnLoanGurantorsReportAsync(string member_No, string path, object userState) {
            if ((this.FnLoanGurantorsReportOperationCompleted == null)) {
                this.FnLoanGurantorsReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnLoanGurantorsReportOperationCompleted);
            }
            this.InvokeAsync("FnLoanGurantorsReport", new object[] {
                        member_No,
                        path}, this.FnLoanGurantorsReportOperationCompleted, userState);
        }
        
        private void OnFnLoanGurantorsReportOperationCompleted(object arg) {
            if ((this.FnLoanGurantorsReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnLoanGurantorsReportCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnAtmApplications", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnAtmApplications_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnAtmApplications(string account) {
            this.Invoke("FnAtmApplications", new object[] {
                        account});
        }
        
        /// <remarks/>
        public void FnAtmApplicationsAsync(string account) {
            this.FnAtmApplicationsAsync(account, null);
        }
        
        /// <remarks/>
        public void FnAtmApplicationsAsync(string account, object userState) {
            if ((this.FnAtmApplicationsOperationCompleted == null)) {
                this.FnAtmApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnAtmApplicationsOperationCompleted);
            }
            this.InvokeAsync("FnAtmApplications", new object[] {
                        account}, this.FnAtmApplicationsOperationCompleted, userState);
        }
        
        private void OnFnAtmApplicationsOperationCompleted(object arg) {
            if ((this.FnAtmApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnAtmApplicationsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnAtmBlocking", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnAtmBlocking_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnAtmBlocking(string account, string reasonForBlock) {
            this.Invoke("FnAtmBlocking", new object[] {
                        account,
                        reasonForBlock});
        }
        
        /// <remarks/>
        public void FnAtmBlockingAsync(string account, string reasonForBlock) {
            this.FnAtmBlockingAsync(account, reasonForBlock, null);
        }
        
        /// <remarks/>
        public void FnAtmBlockingAsync(string account, string reasonForBlock, object userState) {
            if ((this.FnAtmBlockingOperationCompleted == null)) {
                this.FnAtmBlockingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnAtmBlockingOperationCompleted);
            }
            this.InvokeAsync("FnAtmBlocking", new object[] {
                        account,
                        reasonForBlock}, this.FnAtmBlockingOperationCompleted, userState);
        }
        
        private void OnFnAtmBlockingOperationCompleted(object arg) {
            if ((this.FnAtmBlockingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnAtmBlockingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Portals:FnChangePassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", ResponseElementName="FnChangePassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Portals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool FnChangePassword(string memberNumber, string currentPass, string newPass) {
            object[] results = this.Invoke("FnChangePassword", new object[] {
                        memberNumber,
                        currentPass,
                        newPass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FnChangePasswordAsync(string memberNumber, string currentPass, string newPass) {
            this.FnChangePasswordAsync(memberNumber, currentPass, newPass, null);
        }
        
        /// <remarks/>
        public void FnChangePasswordAsync(string memberNumber, string currentPass, string newPass, object userState) {
            if ((this.FnChangePasswordOperationCompleted == null)) {
                this.FnChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("FnChangePassword", new object[] {
                        memberNumber,
                        currentPass,
                        newPass}, this.FnChangePasswordOperationCompleted, userState);
        }
        
        private void OnFnChangePasswordOperationCompleted(object arg) {
            if ((this.FnChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnChangePasswordCompleted(this, new FnChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnUpdatePasswordCompletedEventHandler(object sender, FnUpdatePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnUpdatePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnUpdatePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void MiniStatementCompletedEventHandler(object sender, MiniStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MiniStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MiniStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnMemberStatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnFosaStatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FndividentstatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnLoanGuranteedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnLoanRepaymentSheduleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnLoanGurantorsReportCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnAtmApplicationsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnAtmBlockingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FnChangePasswordCompletedEventHandler(object sender, FnChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591